
# Run rules against a single filing for a specific rule
python ~/Arelle/Arelle-master/arellecmdline.py --plugins 'xule|transforms/SEC|validate/EFM|inlineXbrlDocumentSet' -f https://www.sec.gov/Archives/edgar/data/1329842/000141057825001608/0001410578-25-001608-xbrl.zip -v --xule-time .000 --xule-debug --noCertificateCheck   --logFile  /Users/campbellpryde/Documents/GitHub/dqc/dqc_us_rules/tests/output/testRule195.xml --xule-rule-set  /Users/campbellpryde/Documents/GitHub/dqc/dqc_us_rules/dqc_us_rules/dqc-us-2024-V28-ruleset.zip  --httpuseragent campbell.pryde@xbrl.us --xule-crash --xule-rule-stats-log  --xule-run-only DQC.US.0195.10625  --xule-rule-stats-log

# Run rules against a single filing
python ~/Arelle/Arelle-master/arellecmdline.py --plugins 'xule|transforms/SEC|validate/EFM|inlineXbrlDocumentSet' -f https://www.sec.gov/Archives/edgar/data/1329842/000141057825001608/0001410578-25-001608-xbrl.zip -v --xule-time .000 --xule-debug --noCertificateCheck   --logFile  /Users/campbellpryde/Documents/GitHub/dqc/dqc_us_rules/tests/output/testRule195.xml --xule-rule-set  /Users/campbellpryde/Documents/GitHub/dqc/dqc_us_rules/dqc_us_rules/dqc-us-2024-V28-ruleset.zip  --httpuseragent campbell.pryde@xbrl.us --xule-crash --xule-rule-stats-log

# Generate Taxonomy QNames
python ~/Arelle/Arelle-master/arellecmdline.py  --plugin xule-old/savexuleqnames --xule-qnames-dir '/Users/campbellpryde/Documents/GitHub/xule.dqc/dqc_us_rules/taxonomy/ifrs/2025' --xule-qnames-format json -f 'http://xbrl.ifrs.org/taxonomy/2025-03-27/full_ifrs_entry_point_2025-03-27.xsd'

# Compile ruleset for a specific year (non - sec)
python3.12 ~/arelle/Arelle-master/arellecmdline.py --plugins xule --xule-compile /Users/campbellpryde/Documents/GitHub/dqc/dqc_us_rules/dqc_us_rules/source/us/2025 --xule-rule-set /Users/campbellpryde/Documents/GitHub/dqc/dqc_us_rules/dqc_us_rules/dqc-us-2025-V29-ruleset.zip --xule-crash --xule-crash --xule-stack-size=20 --xule-compile-workers=0


# Create json constants file. This compiles the 
python ~/Arelle/Arelle-master/arellecmdline.py --plugin xule --xule-rule-set /Users/campbellpryde/Documents/GitHub/dqc/dqc_us_rules/dqc_us_rules/dqc-us-2024-V29-ruleset.zip  --xule-output-constants "ACCRUAL_ITEMS,CALC_RELATIONSHIPS,MEMBER_USGAAP_FAIR_VALUE,DEP_CONCEPTS,DEP_EBP_CONCEPTS,DEFINED_BENEFIT_COST_EXT_ENUM,BANKING_MEASURES_BETWEEN_ZERO_AND_ONE,DEFINED_BENEFIT_COST_FS_LINE_ITEMS,DERIVATIVE_LIABILITIES_FS_LINE_ITEMS,DERIVATIVE_ASSETS_FS_LINE_ITEMS,OCI_SECURITY_RELATED_ITEMS,LIQUIDATION_BASIS_CONCEPTS,TAXONOMY_DEFAULTS,NONALLOWED_ROOT_ELEMENTS_CASHFLOW,NETWORK_730000_TARGET_NON_ABSTRACT_QNAMES,MBR_RECL_OUT_ACCUM_CMP_INC_AXS,MEM_LEG_ENT_AXS,MEM_FHLB_AXS,MBR_SCH_EQT_INV_NM_AXS,MBR_PLN_NM_AXS,MEM_RNG_AXS,MEM_SRT_CUR_AXS,MEM_CUR_AXS,MEM_POS_AXS,MEM_FAR_VAL_MSR_FRQ_AXS,MEM_FAR_VAL_MSR_BAS_AXS,DEF_FAR_VAL_MSR_BAS_AXS,MEM_HDG_DSG_AXS,MEM_PRD_SVC_AXS,MEM_AIR_TP_AXS,MEM_SCH_MPR_INS_AXS,MEM_PPE_TP_AXS,MEM_RSV_QTY_RSV_AXS,MEM_PUB_UTL_INV_AXS,MEM_CON_ITM_AXS,MEM_NOT_ALLOWED_RET_TREE,MEM_AWD_DT_AXS,MEM_SUB_EVT_AXS,MBR_STM_EQY_CMP_AXS,MBR_STM_CLS_STK_AXS,MBR_STM_SCN_AXS,MBR_PRF_UNT_NM_AXS,MBR_RET_PLN_NM_AXS,MBR_OWNRSHP_AXS,MBR_MAJ_CST_AXS,MBR_BUS_ACQ_AXS,MBR_STM_BIS_SEG_AXS,MBR_AST_ACQ_AXS,MBR_STM_GEO_AXS,FINANCIAL_DATA_EQUITY_METHOD_INVESTMENTS,NCI,NON_FINANCIAL_DATA_EMI,EXCLUDE_NON_NEG_STRING_MEMBERS,EXCLUDE_NON_NEG_MEMBERS,EXCLUDE_NON_NEG_AXIS_MEMBERS_PRE,EXCLUDE_NON_NEG_AXIS_MEMBERS,EXCLUDE_NON_NEG_AXIS,effective_dates,NON_NEG_ITEMS,DIM_EQUIVALENTS,EXTENSION_ITEMS,ELEMENTS_EXCLUDED_FROM_RULE,CHILD_ELEMENTS_PROMOTABLE_TO_SIBLING_OF_PARENT_ELEMENT,SIBLINGS_DEMOTABLE_TO_CHILD,CHILD_ELEMENTS_PROMOTABLE_TO_SIBLING,PARENT_ELEMENTS_WITH_CHILDREN_PROMOTABLE_TO_SIBLING,SIBLING_ELEMENTS_WITH_SIBLINGS_DEMOTABLE_TO_DESCENDANT,MATURITY_SCHEDULE_ELEMENTS,MESSAGE_FOR_RULE_9277,MESSAGE_FOR_RULE_9278,NETWORK440000,NETWORK606000,NON_CF_ITEMS,SET_NON_CF_ABSTRACTS1,SSH_EXCEPTIONS,ASSET_TYPES,SET_CONCENTRATION_RISK_ITEMS,SET_BENCHMARK_ITEMS,TRANSITION_ELTS_1,TRANSITION_ELTS_2,ALLOWABLE_FINANCING_ITEMS,NON_FINANCING_DESCENDANTS,NON_INVESTING_DESCENDANTS,FILIN_COMPONENTS_OF_NET_INC_LOSS,CHG_IN_OP_CAPTL,ECD_ADJ_TO_COMP_MBRS,APIC_ADJUSTMENTS,AOCI_MEMBERS,OCI_CONCEPTS,NI_CONCEPTS,REL_PTY_STATUS_ENUM,ASU201613_TRANSITION_ELEMENTS,DIM_EQUIV_NAMES,INCOME_STATEMENT_CONCEPTS,EXT_ENUM,IDENTIFICATION,PPE_MEMBERS,INTANGIBLE_FINITE_ASSETS_MEMBERS,INTANGIBLE_INDEFINITE_ASSETS_MEMBERS,INTANGIBLE_MONETARY_ITEMS,INTANGIBLE_DURATION_ITEMS" --xule-output-constants-file /Users/campbellpryde/Documents/GitHub/dqc/dqc_us_rules/dqc_us_rules/dqcrt-us-2024-constants.json -f https://www.sec.gov/Archives/edgar/data/1329842/000141057825001608/0001410578-25-001608-xbrl.zip	--httpuseragent campbell.pryde@xbrl.us


# Create compiled ruleset file including json file
python ~/Arelle/Arelle-master/arellecmdline.py  --plugins xule  --xule-compile /Users/campbellpryde/Documents/GitHub/dqc/dqc_us_rules/dqc_us_rules/source/us/2024 --xule-rule-set /Users/campbellpryde/Documents/GitHub/dqc/dqc_us_rules/dqc_us_rules/dqc-us-2024-V29-SEC-ruleset.zip --xule-crash --xule-args-file /Users/campbellpryde/Documents/GitHub/dqc/dqc_us_rules/dqc_us_rules/dqcrt-us-2024-constants.json --xule-crash --xule-stack-size=20 --xule-compile-workers=0


# Run rules with constants json file.
python ~/Arelle/Arelle-master/arellecmdline.py --plugins 'xule|transforms/SEC|validate/EFM|inlineXbrlDocumentSet' -f https://www.sec.gov/Archives/edgar/data/1329842/000141057825001608/0001410578-25-001608-xbrl.zip -v --xule-time .000 --xule-debug --noCertificateCheck   --logFile  /Users/campbellpryde/Documents/GitHub/dqc/dqc_us_rules/tests/output/testRule195.xml --xule-rule-set  /Users/campbellpryde/Documents/GitHub/dqc/dqc_us_rules/dqc_us_rules/dqc-us-2024-V29-SEC-ruleset.zip  --httpuseragent campbell.pryde@xbrl.us --xule-crash --xule-rule-stats-log  --xule-run-only DQC.US.0195.10625  --xule-rule-stats-log