###

# @name login
POST {{site_url}}/oauth2/token HTTP/1.1
Content-type: application/x-www-form-urlencoded

grant_type={{grant_type}}
&client_id={{client_id}}
&client_secret={{client_secret}}
&username={{username}}
&password={{password}}


###
#Get fact metadata

get {{site_url}}/api/v1/meta/fact
Authorization: Bearer {{login.response.body.access_token}}

###
#Get concept metadata

get {{site_url}}/api/v1/meta/concept
Authorization: Bearer {{login.response.body.access_token}}

###
#Get report metadata
get {{site_url}}/api/v1/meta/report
Authorization: Bearer {{login.response.body.access_token}}

###
#Get company cik
@entity_name = cisco
@fields = entity.name.sort(ASC),entity.cik

# @name cik
GET {{site_url}}/api/v1/entity/search?fields={{fields}}&entity.name={{entity_name}}
Authorization: Bearer {{login.response.body.access_token}}


###

#10K filing for SIC Code
@report_sic-code = 6798
@fields1 = report.filer-category,report.limit(20),report.sic-code,entity.cik,report.filing-date,report.entity-name,report.accession


GET {{site_url}}/api/v1/report/search?report.document-type=10-Q&report.period-index=1&fields={{fields1}}&report.filer-category=Large%20Accelerated%20Filer&report.sic-code={{report_sic-code}}&report.is-most-current=true
Authorization: Bearer {{login.response.body.access_token}}


###

@document-type = 10-K,10-Q
@number-filings = 10
@fields-latest-filings = report.entity-name,report.limit({{number-filings}}),report.sec-url,report.filing-date.sort(DESC),report.document-type

#get latest filings
GET {{site_url}}/api/v1/report/search?report.is-most-current=true&fields={{fields-latest-filings}}&report.document-type={{document-type}}
Authorization: Bearer {{login.response.body.access_token}}

###

#Errors by filing

@fields_assertion = assertion.code,assertion.detail,assertion.effective-date,assertion.run-date,entity.name,report.accession,report.base-taxonomy,report.creation-software,report.document-type,report.filing-date,report.sec-url

@accession = 0001213900-20-012125

GET {{site_url}}/api/v1/assertion/search?fields={{fields_assertion}}&report.accession={{accession}}&assertion.source=DQC&assertion.code=DQC.US.0001.62
Authorization: Bearer {{login.response.body.access_token}}

###
@fields_rule_assertion = assertion.code,assertion.detail,assertion.effective-date,assertion.run-date,entity.name,report.accession,report.base-taxonomy,report.creation-software,report.document-type,report.filing-date,report.sec-url,assertion.limit(100),assertion.type

@assertion_code = DQC.US.0001.62

GET {{site_url}}/api/v1/assertion/search?fields={{fields_rule_assertion}}&assertion.source=DQC&assertion.code={{assertion_code}}
Authorization: Bearer {{login.response.body.access_token}}

###

#Get all errors for filing

@entity_cik = {{cik.response.body.$.data[0]['entity.cik']}}

GET {{site_url}}/api/v1/assertion/search?fields={{fields_rule_assertion}}&assertion.source=DQC&entity.cik={{entity_cik}}
Authorization: Bearer {{login.response.body.access_token}}

###
#Get facts for a dts

@dts_id = 298003

GET {{site_url}}/api/v1/fact/search?fields=concept.namespace,concept.local-name,dimensions,fact.limit(10)&dts.id={{dts_id}}
Authorization: Bearer {{login.response.body.access_token}}

###

#get text from filings
GET {{site_url}}/api/v1/document/search?document.text-search=tsunami%20%3C%3C%20earthquake&fields=entity.name,entity.cik,document.id,report.filing-date,document.example,document.limit(10)
Authorization: Bearer {{login.response.body.access_token}}


###
#Validate Filing
POST {{site_url}}/api/v1/assertion/validate
Authorization: Bearer {{login.response.body.access_token}}
Content-Type: multipart/form-data; boundary=--myBoundry

----myBoundry
Content-Disposition: form-data; name="status"

approved
----myBoundry
Content-Disposition: form-data; name="efm"

pragmatic
----myBoundry
Content-Disposition: form-data; name="Task"

checkfiling
----myBoundry
Content-Disposition: form-data; name="format"

xml
----myBoundry
Content-Disposition: form-data; name="file"; filename="0000829224-20-000078-xbrl.zip"
Content-Type: application/zip

< /Users/campbellpryde/Downloads/0000829224-20-000078-xbrl.zip

----myBoundry--