@startuml dividends_Per_Share
title "When to use CommonStockDividendsPerShareDeclared versus DividendsPayableAmountPerShare"
!pragma useVerticalIf on
start

 
 if (   Is the dividend 
    announcement after
    the period end
    of the report?) then (no)
   
       : Use CommonStockDividendsPerShareDeclared;
      end
 else (yes)
    

                :Use DividendsPayableAmountPerShare ;
               
                        
    
end

@enduml