@startuml dividends_Per_Share
title "When to use the Dividends Axis"
!pragma useVerticalIf on
start

 
 if (Has the filer reported the payment, 
   record and declaration dates
  associated with each Dividend?) then (no)

   if (Are multiple dividends reported 
   in the same reporting period?) then (no)

      
      if (   Is the dividend declared after
      the Reporting Period end?) then (no)
      
      : Do not use the DividendsAxis;
      end
      
 else (yes)
   if (  Is the dividend associated 
   with a given reporting period 
   (Not the sum of individual dividends)) then (no)
   : Do not use the DividendsAxis;
   end 
      
   else (yes)
   endif

    endif 
      

      
 else (yes)

    endif 
      
      
 else (yes)

    endif 

                 : Use DividendsAxis;
               
                        
    
end

@enduml