@startuml dividends_Per_Share
title "When to use the Dividends Axis"
!pragma useVerticalIf on
start

 
 if (Has the filer reported the payment, 
   record and declaration dates
  associated with each Dividend? 
  (Reporting a dividend event)) then (no)

   if (Are multiple dividends reported 
   in the same reporting period?
   (Reporting summary divdend 
   information)) then (no)
      : Do NOT use the DividendsAxis;
      end
         
   else (yes)

   endif
else (yes)
    endif 
      
: Use DividendsAxis;
               
                        
    
end

@enduml