name: DataQualityCommittee/dqc_us_rules
on:
  workflow_dispatch:
  workflow_run:
    workflows: [Run Tests]
    types:
        - completed
  #push:
  #  branches:
  #  - master
  #  - "/v.*/"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  EXPECTED: "./tests/output"
  CURDIR: "$(pwd)"
  XULE_VERSION: '23694.1'
  GH_SLUG: https://github.com/${{ github.repository_owner }}/${{ github.repository }}
  PR_BR: "${TRAVIS_PULL_REQUEST_BRANCH:-${{ github.ref }}}"
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - uses: actions/setup-python@v5.0.0
      with:
        python-version: '3.10'
    - run: pip install -r ./requirements.txt
    - run: pip install Arelle-release==2.22.3
    - run: bash ./travis-run.sh
    - run: echo '===== START LOG FILE =====' && head -3000 log.xml && echo '===== END LOG FILE ====='
    - run: echo '===== START REPORT FILE =====' && head -3000 report.txt && echo '===== END REPORT FILE ====='
    - run: echo '===== START REPORT HTML FILE =====' && head -3000 report.html && echo '===== END REPORT HTML FILE ====='
    strategy:
      matrix:
        include:
        - INFILES: '[{"file":"https://www.sec.gov/Archives/edgar/data/1552033/000155203321000008/ck0001552033-20201231.htm","xule_run_only":"DQC.US.0152.10116"}]'
          EXFILES: "$EXPECTED/DQC.US.0152.10116_TU_US-2020.xml"
    env:
      INFILES: "${{ matrix.INFILES }}"
